### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by Bra1nsen** [codesqueak/pi_pico_bme280#3]
hello sir,

connected everything as described.

```
Traceback (most recent call last):
  File "<stdin>", line 11, in <module>
  File "/lib/machine/__init__.py", line 2, in <module>
  File "/lib/machine/timer.py", line 7, in <module>
  File "/lib/signal.py", line 13, in <module>
AttributeError: 'NoneType' object has no attribute 'func'
```

i dont know how to fix the lib files .. can you help?

**Comment by Bra1nsen** [comment]
![22](https://user-images.githubusercontent.com/58213050/185482755-6d4fbea8-771f-4449-a19a-6c2e71682893.jpg)
![33](https://user-images.githubusercontent.com/58213050/185482767-7dac0d48-f846-4501-b185-405c63599573.jpg)

**Comment by Bra1nsen** [comment]
if you wondering, its just the pico with a lora hat (sx126x) 

happy greetings from dresden

**Comment by Bra1nsen** [comment]
ok found the mistake, i installed the package machine manually..

**Comment by codesqueak** [comment]
Hi

Just picked up your comment. Apologies for the slow response.

Glad you found the issue
